// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/labstack/echo/v4"
	"github.com/vnnyx/article-service/graph/repository"
	"github.com/vnnyx/article-service/graph/routes"
	"github.com/vnnyx/article-service/graph/usecase"
	"github.com/vnnyx/article-service/internal/infrastructure"
)

// Injectors from injector.go:

func InitializeRoute(e *echo.Echo) *routes.Route {
	config := infrastructure.NewConfig()
	database := infrastructure.NewMongoDatabase(config)
	authorRepository := repository.NewAuthorRepository(database)
	authorUC := usecase.NewAuthorUC(authorRepository)
	articleRepository := repository.NewArticleRepository(database)
	articleUC := usecase.NewArticleUC(articleRepository)
	route := routes.NewRoute(e, authorUC, articleUC)
	return route
}
